"""Table contract for the BIT revision (Task 12).

The Online Resource tables are generated by scripts/generate_bit_tables.py from frozen records; the article's
two hand-typeset tables (methods/orientation and adaptive tests) must agree with the same records.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from fractions import Fraction
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import generate_bit_tables as gbt  # noqa: E402

TABLES = ROOT / "results" / "bit_revision" / "tables"
MANUSCRIPT = ROOT.parent / "manuscript"
HEADERS = {
    "extrapolation_table.tex": "% Table S2 data; generated from the archived records\n",
    "tolerance_sweep_table.tex": "% Table S3 data; generated from the archived records\n",
    "guard_telemetry_table.tex": "% Table S4 data; generated from the archived records\n",
}
GENERATED = {
    "extrapolation_table.tex": gbt.extrapolation_table,
    "tolerance_sweep_table.tex": gbt.tolerance_sweep_table,
    "guard_telemetry_table.tex": gbt.guard_telemetry_table,
}


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def tex_number(cell: str) -> Fraction | float:
    """Parse '$-1/2$', '$\\tfrac{97}{120000}$', '$7.92\\times10^{-4}$', '72', '0'."""
    s = cell.strip().strip("$").replace("\\,", "")
    m = re.fullmatch(r"(-?)\\tfrac\{(\d+)\}\{(\d+)\}", s)
    if m:
        return Fraction(int(m.group(2)), int(m.group(3))) * (-1 if m.group(1) else 1)
    m = re.fullmatch(r"(-?\d+(?:\.\d+)?)\\times10\^\{(-?\d+)\}", s)
    if m:
        return float(m.group(1)) * 10.0 ** int(m.group(2))
    m = re.fullmatch(r"-?\d+/\d+", s)
    if m:
        return Fraction(s)
    return Fraction(s)


def article_table(label: str) -> str:
    """The tabular* environment of the article table carrying `label`, from the working sections or, in the shipped
    archive, from the flattened article source `manuscript_source/main.tex`."""
    candidates = [MANUSCRIPT / "sec03_cp_criterion.tex", MANUSCRIPT / "sec06_certification_and_examples.tex", ROOT / "manuscript_source" / "main.tex"]
    for p in candidates:
        if p.exists():
            tex = p.read_text(encoding="utf-8")
            for m in re.finditer(r"\\begin\{table\}.*?\\end\{table\}", tex, re.S):
                if f"\\label{{{label}}}" in m.group(0):
                    return re.search(r"\\begin\{tabular\*\}.*?\\end\{tabular\*\}", m.group(0), re.S).group(0)
    pytest.skip(f"article source with table {label} not available (needs ../manuscript or manuscript_source/main.tex)")


def table_rows(tex: str) -> list[list[str]]:
    body = tex.split(r"\midrule", 1)[1]
    body = re.split(r"\\bottomrule|\\botrule", body)[0]
    rows = []
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("%"):
            continue
        cells = [c.strip() for c in line.rstrip("\\").split("&")]
        rows.append(cells)
    return rows


# ---------------------------------------------------------------------------
# generated Online Resource tables
# ---------------------------------------------------------------------------
def test_manifest_hashes_match_inputs_and_outputs():
    manifest = json.loads((TABLES / "manifest.json").read_text(encoding="utf-8"))
    for key, path in gbt.INPUTS.items():
        assert manifest["inputs"][key] == sha256(path), key
    for name in GENERATED:
        assert manifest["outputs"][name] == sha256(TABLES / name), name


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_generated_table_is_deterministic_and_unedited(name):
    text = (TABLES / name).read_text(encoding="utf-8")
    header = HEADERS[name]
    assert gbt.HEADERS[name] == header
    assert text.startswith(header)
    assert text[len(header):] == GENERATED[name]()
    assert GENERATED[name]() == GENERATED[name]()


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_generated_table_shape_and_rules(name):
    text = (TABLES / name).read_text(encoding="utf-8")
    assert r"\botrule" not in text  # article-class Online Resource uses booktabs
    assert text.count(r"\toprule") == 1 and text.count(r"\midrule") == 1 and text.count(r"\bottomrule") == 1
    spec = re.search(r"\\begin\{tabular\}\{@\{\}([lcr]+)@\{\}\}", text).group(1)
    ncol = len(spec)
    header = text.split(r"\toprule", 1)[1].split(r"\midrule", 1)[0]
    header_rows = [r for r in header.split(r"\\") if "&" in r]
    assert header_rows
    for hrow in header_rows:  # a grouped header row may span columns with \multicolumn{k}
        spans = [int(k) for k in re.findall(r"\\multicolumn\{(\d+)\}", hrow)]
        assert hrow.count("&") + 1 - len(spans) + sum(spans) == ncol, hrow
    for row in table_rows(text):
        assert len(row) == ncol, row


@pytest.mark.skipif(not MANUSCRIPT.exists(), reason="the article's LaTeX sources (../manuscript) are not included in this archive")
@pytest.mark.parametrize("name", sorted(GENERATED))
def test_manuscript_copy_is_byte_identical(name):
    assert (MANUSCRIPT / name).read_bytes() == (TABLES / name).read_bytes()


# ---------------------------------------------------------------------------
# article Table 1 (first defects and local orientation) against the corollary record
# ---------------------------------------------------------------------------
ARTICLE_NAMES = {
    "Forward Euler": "Forward Euler",
    "Two-stage order two (Heun)": "Heun RK2",
    "SSPRK(3,3)": "SSPRK(3,3)",
    "Classical RK4": "Classical RK4",
    "Dormand--Prince 5 (principal)": "Dormand-Prince 5 principal formula",
    "Dormand--Prince 4 (embedded)": "Dormand-Prince embedded 4 formula",
    "Backward Euler": "Backward Euler",
    "Implicit midpoint": "Implicit midpoint",
}


def test_article_methods_table_matches_corollary_record():
    data = json.loads(gbt.INPUTS["corollary"].read_text(encoding="utf-8"))
    rec = {(r["method"], r["n"]): r for r in data["method_table"]}
    table = article_table("tab:methods")
    rows = table_rows(table)
    assert len(rows) == 9
    seen = set()
    for name, p, m, eta, coef, small in rows:
        p, m = int(p), int(m)
        eta_v, coef_v = tex_number(eta), tex_number(coef)
        if name.startswith("Richardson"):
            r = rec[("Classical RK4", 2)]
            assert (p, m) == (5, 6)
            assert eta_v == Fraction(r["defect_coefficient"]) == Fraction(-1, 4320)
        else:
            r = rec[(ARTICLE_NAMES[name], 2)]
            assert p == r["p"] and m == p + 1
            assert eta_v == Fraction(r["eta_p1"])
        G_m0 = 1 - Fraction(1, 2 ** (m - 1))
        assert coef_v == (-1) ** m * eta_v * G_m0, name
        assert small == ("CPTP" if coef_v > 0 else "non-CPTP"), name
        seen.add(name)
    assert seen == set(ARTICLE_NAMES) | {"Richardson extrapolate of RK4 ($n=2$)"}


# ---------------------------------------------------------------------------
# article adaptive table against the frozen sweep and the v3.4 guard rows
# ---------------------------------------------------------------------------
def test_article_adaptive_table_matches_frozen_records():
    import csv

    with gbt.INPUTS["sweep"].open(newline="", encoding="utf-8") as f:
        sweep = {(r["policy"], float(r["tolerance"])): r for r in csv.DictReader(f)}
    v34 = json.loads(gbt.INPUTS["v34"].read_text(encoding="utf-8"))
    guard = {r["scenario"]: r for r in v34["scientifically_useful_candidate_guard_rows"]}
    table = article_table("tab:adaptive")
    rows = table_rows(table)
    assert len(rows) == 7
    policy_of = {"error only": "error_only", "guard, rotating fallback": "guard_rotating_fallback", "rotating frame": "rotating_frame", "Strang, exact subflows": "strang"}
    scenario_of = {"buffered (1)": "buffered_projection", "buffered (2)": "buffered_direct", "near saddle": "near_saddle_projection"}
    for case, policy, err, eig, dpf, stages in rows:
        if case == "boundary":
            src = sweep[(policy_of[policy], 1e-3)]
        else:
            src = guard[scenario_of[case]]
            assert policy == "guard"
        err_v = float(tex_number(err))
        assert abs(err_v - float(src["global_normalized_choi_error"])) <= 0.005 * abs(err_v), (case, policy)
        eig_src = float(src["minimum_step_choi_eigenvalue"])
        if eig.strip().startswith(r"$\ge"):
            assert eig_src >= -1e-15, (case, policy)
        else:
            eig_v = float(tex_number(eig))
            assert abs(eig_v - eig_src) <= 0.05 * abs(eig_v), (case, policy)
        if dpf.strip() == "--":
            # policies without the guard do not classify their accepted candidates
            assert src.get("controller_policy", "candidate_guard") != "candidate_guard" or case != "boundary" or policy == "error only"
            assert policy in ("error only", "rotating frame", "Strang, exact subflows"), (case, policy)
        else:
            d, p_, f_ = (int(v) for v in dpf.split("/"))
            assert d == int(float(src["direct_accepts"])) and p_ == int(float(src["projected_accepts"]))
            assert f_ == int(float(src["rotating_accepts"])) + int(float(src["exact_fallback_accepts"]))
            assert d + p_ + f_ == int(float(src["accepted_steps"])), (case, policy)
        assert int(stages) == int(float(src["rhs_stage_evaluations"])), (case, policy)


# ---------------------------------------------------------------------------
# generated sweep table against the CSV (row selection and formatting)
# ---------------------------------------------------------------------------
def test_generated_sweep_table_covers_all_boundary_rows():
    import csv

    with gbt.INPUTS["sweep"].open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    tex = (TABLES / "tolerance_sweep_table.tex").read_text(encoding="utf-8")
    assert len(table_rows(tex)) == len(rows) == 16
    for r in rows:
        assert str(int(float(r["accepted_steps"]))) in tex
