"""Contract tests for the BIT source auditor and package builder.

Rules are exercised on small synthetic manuscripts (fast, hermetic) and, when the article's LaTeX sources are
present in `../manuscript`, on the real source (source-level rules only; the packaged artifacts are audited by
`reproduce_bit.py manuscript-contract` and by the package builder itself).
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
import zipfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import audit_bit_source as abs_  # noqa: E402
import build_bit_package as bbp  # noqa: E402

MANUSCRIPT = ROOT.parent / "manuscript"

GOOD_MAIN = r"""
\documentclass[pdflatex,sn-mathphys-num]{sn-jnl}
\begin{document}
\title[Short]{A good title}
\author*[1]{\fnm{Ada} \sur{Lovelace}}\email{ada@example.org}
\author[2]{\fnm{Carl} \sur{Runge}}\email{carl@example.org}
\affil*[1]{\orgname{Uni A}, \orgaddress{\city{A}, \country{X}}}
\affil[2]{\orgname{Uni B}, \orgaddress{\city{B}, \country{Y}}}
\abstract{%s}
\keywords{one, two, three, four}
\pacs[MSC Classification]{65L06, 65L20}
\maketitle
\input{sec01}
\backmatter
\bmhead{Supplementary information}
Online Resource 1 (\texttt{ESM\_1.pdf}) contains details.
\input{declarations}
\bibliography{references}
\end{document}
"""
GOOD_SEC = r"""
\section{Intro}\label{sec:intro}
Text with a citation \cite{KeyA} and a reference to Fig.~\ref{fig:one} and Theorem~\ref{thm:main}.
\begin{theorem}\label{thm:main} Statement. \end{theorem}
\begin{figure}[tbp]\centering\includegraphics[width=\textwidth]{Fig1.eps}
\caption{A caption without final period}\label{fig:one}\end{figure}
"""
GOOD_DECL = r"""
\bmhead{Acknowledgements}
Thanks.
\section*{Declarations}
\bmhead{Funding}
None.
\bmhead{Competing interests}
The authors have no competing interests to declare that are relevant to the content of this article.
\bmhead{Ethics approval and consent to participate}
Not applicable.
\bmhead{Consent for publication}
Not applicable.
\bmhead{Data availability}
All data supporting the findings are contained in the archive described below and regenerated by its commands.
\bmhead{Code availability}
The archive is available at [PERSISTENT DOI OR REPOSITORY URL OF THE ARCHIVED RELEASE TO BE INSERTED BEFORE SUBMISSION].
\bmhead{Author contributions}
A.L. and C.R. did everything.
\bmhead{Use of generative artificial intelligence}
Large language model tools were used substantively in the preparation of this work: for drafting, restructuring, and editing the text, for writing parts of the verification code, and for literature searches; the authors checked every statement and every result and take full responsibility for the content of this article. [THIS STATEMENT MUST BE REVIEWED AND APPROVED BY ALL AUTHORS BEFORE SUBMISSION.]
"""
GOOD_BIB = r"""
@article{KeyA,
  author = {Doe, J.},
  title = {A paper},
  journal = {J. Test},
  volume = {1},
  pages = {1--2},
  year = {2020},
  doi = {10.1000/test}
}
"""
GOOD_ESM = r"""
\documentclass{article}
\usepackage{graphicx}
\newcommand{\artnum}[1]{\csname artnum@#1\endcsname}
\input{article_numbers}
\title{Online Resource 1 for ``A good title''}
\author{Ada Lovelace and Carl Runge \\ Corresponding author: ada@example.org}
\begin{document}
\maketitle
Article Theorem~\artnum{thm:main} is used. See Fig.~\ref{fig:S1}.
\begin{figure}\includegraphics{FigS1.eps}\caption{S}\label{fig:S1}\end{figure}
\end{document}
"""
GOOD_COVER = r"""
\documentclass{article}
\newenvironment{letterbody}{}{}
\begin{document}
Dear Editor,
\begin{letterbody}
We submit ``A good title'' to \textit{BIT}. It is short. [NOT-UNDER-CONSIDERATION-ELSEWHERE STATEMENT TO BE CONFIRMED BY THE AUTHORS BEFORE SUBMISSION]
\end{letterbody}
Sincerely
\end{document}
"""


def make_manuscript(tmp_path: Path, abstract_words: int = 180, **overrides) -> Path:
    m = tmp_path / "manuscript"
    m.mkdir(parents=True)
    abstract = " ".join(f"w{i}" for i in range(abstract_words))
    files = {
        "main.tex": GOOD_MAIN % abstract,
        "sec01.tex": GOOD_SEC,
        "declarations.tex": GOOD_DECL,
        "references.bib": GOOD_BIB,
        "ESM_1.tex": GOOD_ESM,
        "cover_letter.tex": GOOD_COVER,
        "article_numbers.tex": "\\expandafter\\gdef\\csname artnum@thm:main\\endcsname{1}\n",
        "Fig1.eps": "%!PS-Adobe-3.0 EPSF-3.0\n",
        "FigS1.eps": "%!PS-Adobe-3.0 EPSF-3.0\n",
        "sn-jnl.cls": "% class\n",
        "sn-mathphys-num.bst": "% bst\n",
    }
    files.update(overrides)
    for name, content in files.items():
        if content is None:
            continue
        (m / name).write_text(content, encoding="utf-8")
    return m


def rule(result: dict, rule_id: str) -> dict:
    for r in result["rules"]:
        if r["id"] == rule_id:
            return r
    raise KeyError(rule_id)


# ---------------------------------------------------------------------------
# source rules
# ---------------------------------------------------------------------------
def test_good_synthetic_manuscript_passes_all_source_rules(tmp_path):
    res = abs_.run_audit(make_manuscript(tmp_path), status="PRE_SUBMISSION")
    failed = [r["id"] for r in res["rules"] if r["status"] == "FAIL"]
    assert failed == [], failed
    assert res["counts"]["FAIL"] == 0


def test_abstract_word_count_bounds(tmp_path):
    res = abs_.run_audit(make_manuscript(tmp_path, abstract_words=120), status="PRE_SUBMISSION")
    assert rule(res, "abstract_word_count")["status"] == "FAIL"
    res = abs_.run_audit(make_manuscript(tmp_path / "b", abstract_words=260), status="PRE_SUBMISSION")
    assert rule(res, "abstract_word_count")["status"] == "FAIL"


def test_keyword_and_msc_rules(tmp_path):
    bad = (GOOD_MAIN % "x " * 1).replace(r"\keywords{one, two, three, four}", r"\keywords{one, two, three}").replace(r"\pacs[MSC Classification]{65L06, 65L20}", r"\pacs[MSC Classification]{}")
    m = make_manuscript(tmp_path, **{"main.tex": bad})
    res = abs_.run_audit(m, status="PRE_SUBMISSION")
    assert rule(res, "keyword_count")["status"] == "FAIL"
    assert rule(res, "msc_codes_present")["status"] == "FAIL"


def test_cover_letter_word_limit(tmp_path):
    long_cover = GOOD_COVER.replace("It is short.", " ".join(["word"] * 160))
    res = abs_.run_audit(make_manuscript(tmp_path, **{"cover_letter.tex": long_cover}), status="PRE_SUBMISSION")
    assert rule(res, "cover_letter_word_count")["status"] == "FAIL"


def test_unresolved_reference_and_missing_citation_key(tmp_path):
    sec = GOOD_SEC.replace(r"\ref{thm:main}", r"\ref{thm:missing}").replace(r"\cite{KeyA}", r"\cite{KeyA,KeyB}")
    res = abs_.run_audit(make_manuscript(tmp_path, **{"sec01.tex": sec}), status="PRE_SUBMISSION")
    assert rule(res, "article_refs_resolve")["status"] == "FAIL"
    assert rule(res, "citation_keys_in_bibliography")["status"] == "FAIL"


def test_markers_are_listed_for_pre_submission_and_fatal_for_final(tmp_path):
    m = make_manuscript(tmp_path)
    pre = abs_.run_audit(m, status="PRE_SUBMISSION")
    r = rule(pre, "unresolved_markers")
    assert r["status"] == "PASS" and len(r["detail"]["deliberate_markers"]) >= 3
    final = abs_.run_audit(m, status="FINAL")
    assert rule(final, "unresolved_markers")["status"] == "FAIL"
    assert rule(final, "package_status_consistent")["status"] == "FAIL"


def test_unknown_marker_words_fail_even_before_submission(tmp_path):
    sec = GOOD_SEC + "\nTODO fix this sentence.\n"
    res = abs_.run_audit(make_manuscript(tmp_path, **{"sec01.tex": sec}), status="PRE_SUBMISSION")
    assert rule(res, "unresolved_markers")["status"] == "FAIL"


def test_jcp_boilerplate_and_stale_terms_fail(tmp_path):
    m = make_manuscript(tmp_path, **{"Highlights.txt": "bullet"})
    res = abs_.run_audit(m, status="PRE_SUBMISSION")
    assert rule(res, "no_jcp_boilerplate_files")["status"] == "FAIL"
    sec = GOOD_SEC + "\nThe candidate record is stored in the Supplemental Material of the Journal of Computational Physics version.\n"
    res = abs_.run_audit(make_manuscript(tmp_path / "b", **{"sec01.tex": sec}), status="PRE_SUBMISSION")
    assert rule(res, "residue_scan")["status"] == "FAIL"


def test_missing_ai_statement_or_data_availability_fail(tmp_path):
    decl = GOOD_DECL.replace(r"\bmhead{Use of generative artificial intelligence}", r"\bmhead{Something else}")
    res = abs_.run_audit(make_manuscript(tmp_path, **{"declarations.tex": decl}), status="PRE_SUBMISSION")
    assert rule(res, "ai_disclosure_present")["status"] == "FAIL"
    decl = GOOD_DECL.replace(r"\bmhead{Data availability}", r"\bmhead{Data}")
    res = abs_.run_audit(make_manuscript(tmp_path / "b", **{"declarations.tex": decl}), status="PRE_SUBMISSION")
    assert rule(res, "data_availability_present")["status"] == "FAIL"
    assert rule(res, "required_declarations_present")["status"] == "FAIL"


def test_figure_sequence_and_citation_rules(tmp_path):
    sec = GOOD_SEC.replace("Fig1.eps", "Fig2.eps")
    m = make_manuscript(tmp_path, **{"sec01.tex": sec, "Fig2.eps": "%!PS\n"})
    res = abs_.run_audit(m, status="PRE_SUBMISSION")
    assert rule(res, "figures_sequential_and_cited")["status"] == "FAIL"


def test_caption_punctuation_rule(tmp_path):
    sec = GOOD_SEC.replace("A caption without final period", "A caption with a final period.")
    res = abs_.run_audit(make_manuscript(tmp_path, **{"sec01.tex": sec}), status="PRE_SUBMISSION")
    assert rule(res, "caption_style")["status"] == "FAIL"


def test_author_sync_between_article_esm_and_metadata(tmp_path):
    esm = GOOD_ESM.replace("Ada Lovelace and Carl Runge", "Ada Lovelace and Someone Else")
    res = abs_.run_audit(make_manuscript(tmp_path, **{"ESM_1.tex": esm}), status="PRE_SUBMISSION")
    assert rule(res, "authors_synchronized")["status"] == "FAIL"


def test_online_resource_synchronization(tmp_path):
    main = (GOOD_MAIN % "x").replace(r"Online Resource 1 (\texttt{ESM\_1.pdf}) contains details.", "See the supplement.")
    res = abs_.run_audit(make_manuscript(tmp_path, **{"main.tex": main}), status="PRE_SUBMISSION")
    assert rule(res, "online_resource_synchronized")["status"] == "FAIL"


def test_esm_article_numbers_check_uses_build_aux(tmp_path):
    m = make_manuscript(tmp_path)
    build = tmp_path / "build"
    build.mkdir()
    (build / "main.aux").write_text("\\newlabel{thm:main}{{2}{3}{}{}{}}\n", encoding="utf-8")
    (build / "main.log").write_text("no warnings\n", encoding="utf-8")
    res = abs_.run_audit(m, status="PRE_SUBMISSION", build_dir=build)
    assert rule(res, "esm_article_numbers_synchronized")["status"] == "FAIL"


def test_build_log_rules_detect_undefined_references(tmp_path):
    m = make_manuscript(tmp_path)
    build = tmp_path / "build"
    build.mkdir()
    (build / "main.aux").write_text("\\newlabel{thm:main}{{1}{3}{}{}{}}\n", encoding="utf-8")
    (build / "main.log").write_text("LaTeX Warning: Citation `KeyZ' on page 1 undefined on input line 5.\nOverfull \\hbox (12.0pt too wide)\n", encoding="utf-8")
    res = abs_.run_audit(m, status="PRE_SUBMISSION", build_dir=build)
    assert rule(res, "build_log_clean")["status"] == "FAIL"


def test_pdffonts_parser_rejects_bitmap_text_fonts():
    good = ["ABCDEF+CMR10                         Type 1            Builtin          yes yes yes    193  0",
            "[none]                               Type 3            Custom           yes no  no     159  0"]
    ok, info = abs_.parse_pdffonts(good)
    assert ok and info["type3_text_fonts"] == [] and info["type3_fonts"] == 1
    bad = good + ["F43                                  Type 3            Custom           yes no  no     160  0"]
    ok, info = abs_.parse_pdffonts(bad)
    assert not ok and info["type3_text_fonts"] == ["F43"]
    ok, info = abs_.parse_pdffonts(["ABCDEF+CMR10                         Type 1            Builtin          no  yes yes    193  0"])
    assert not ok and info["not_embedded"] == 1


# ---------------------------------------------------------------------------
# builder helpers
# ---------------------------------------------------------------------------
def test_flatten_inlines_inputs_recursively(tmp_path):
    m = make_manuscript(tmp_path)
    flat = bbp.flatten_tex(m / "main.tex")
    assert "\\input{" not in flat
    assert "\\section{Intro}" in flat and "\\bmhead{Funding}" in flat
    assert flat.count("\\documentclass") == 1
    # the flattened file that goes to the journal carries no marker comments naming the inlined files
    assert "%% ----" not in flat and "sec01" not in flat and "declarations.tex" not in flat


def test_review_variant_adds_lineno_option(tmp_path):
    m = make_manuscript(tmp_path)
    flat = bbp.flatten_tex(m / "main.tex")
    review = bbp.review_variant(flat)
    assert "\\documentclass[pdflatex,sn-mathphys-num,lineno]{sn-jnl}" in review
    assert review.count("lineno") == 1
    # the continuous ruler is restarted with a wider even-page offset so that four-digit numbers keep clear of the text
    assert "\\begin{document}\n" + bbp.REVIEW_RULER + "\n" in review
    assert "\\unsetvruler\\setvruler[12bp][1][1][3][1][1.18\\textwidth][18pt]" in review
    assert review.replace(bbp.REVIEW_RULER + "\n", "").replace(",lineno]", "]") == flat
    with pytest.raises(ValueError):
        bbp.review_variant(flat.replace("\\begin{document}", ""))


def test_flat_zip_writer_rejects_nested_and_absolute_names(tmp_path):
    f = tmp_path / "a.txt"
    f.write_text("x", encoding="utf-8")
    z = tmp_path / "out.zip"
    bbp.write_flat_zip(z, {"a.txt": f})
    with zipfile.ZipFile(z) as zf:
        assert zf.namelist() == ["a.txt"]
        assert zf.testzip() is None
    with pytest.raises(ValueError):
        bbp.write_flat_zip(tmp_path / "bad.zip", {"sub/a.txt": f})
    with pytest.raises(ValueError):
        bbp.write_flat_zip(tmp_path / "bad2.zip", {"../a.txt": f})


def test_flat_zip_is_deterministic(tmp_path):
    f = tmp_path / "a.txt"
    f.write_text("x", encoding="utf-8")
    z1, z2 = tmp_path / "1.zip", tmp_path / "2.zip"
    bbp.write_flat_zip(z1, {"a.txt": f})
    bbp.write_flat_zip(z2, {"a.txt": f})
    assert z1.read_bytes() == z2.read_bytes()


def test_zip_verification_detects_tampering(tmp_path):
    f = tmp_path / "a.txt"
    f.write_text("payload", encoding="utf-8")
    z = tmp_path / "out.zip"
    bbp.write_flat_zip(z, {"a.txt": f})
    ok = bbp.verify_flat_zip(z, {"a.txt": f})
    assert ok["crc_ok"] and ok["flat"] and ok["bytes_match"] and ok["members"] == 1
    f.write_text("changed", encoding="utf-8")
    assert not bbp.verify_flat_zip(z, {"a.txt": f})["bytes_match"]


def test_checksum_manifest_roundtrip(tmp_path):
    (tmp_path / "x.bin").write_bytes(b"abc")
    (tmp_path / "y.bin").write_bytes(b"def")
    text = bbp.sha256_manifest([tmp_path / "x.bin", tmp_path / "y.bin"], tmp_path)
    assert hashlib.sha256(b"abc").hexdigest() in text and "x.bin" in text
    assert bbp.verify_sha256_manifest(text, tmp_path) == []
    (tmp_path / "y.bin").write_bytes(b"xyz")
    assert bbp.verify_sha256_manifest(text, tmp_path) == ["y.bin"]


def test_code_allowlist_excludes_environments_caches_and_logs():
    files = bbp.code_archive_files(ROOT)
    names = [p.as_posix() for p in files]
    assert any(n == "reproduce_bit.py" for n in names)
    assert any(n.startswith("src/rk_choi_margin/") for n in names)
    assert any(n.startswith("tests/") for n in names)
    assert any(n == "results/v34/v34_verification.json" for n in names)
    for n in names:
        assert not n.startswith(".venv") and "__pycache__" not in n and ".pytest_cache" not in n
        assert not n.startswith("results/bit_revision/logs/")
        assert not n.startswith("figures_jcp/Graphical_Abstract")
        assert ".egg-info" not in n
        assert not n.endswith((".pyc", ".aux", ".synctex.gz"))


# ---------------------------------------------------------------------------
# real working source (source-level rules only)
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not MANUSCRIPT.exists(), reason="the article's LaTeX sources (../manuscript) are not included in this archive")
def test_real_manuscript_source_rules_pass():
    res = abs_.run_audit(MANUSCRIPT, status="PRE_SUBMISSION")
    failed = {r["id"]: r["detail"] for r in res["rules"] if r["status"] == "FAIL"}
    assert failed == {}, json.dumps(failed, indent=1)[:2000]


def test_explicit_code_allowlist_does_not_ship_unknown_files(tmp_path):
    (tmp_path / "CODE_ARCHIVE_ALLOWLIST.txt").write_text("CODE_ARCHIVE_ALLOWLIST.txt\nreproduce_bit.py\n")
    (tmp_path / "reproduce_bit.py").write_text("print('ok')")
    (tmp_path / "private_notes.txt").write_text("not a release input")
    assert {p.as_posix() for p in bbp.code_archive_files(tmp_path)} == {"CODE_ARCHIVE_ALLOWLIST.txt", "reproduce_bit.py"}


@pytest.mark.parametrize("entry", ["../outside.txt", "main.synctex.gz", "missing.py"])
def test_code_allowlist_rejects_unsafe_temporary_or_missing_entry(tmp_path, entry):
    (tmp_path / "CODE_ARCHIVE_ALLOWLIST.txt").write_text(entry + "\n")
    (tmp_path / "main.synctex.gz").write_text("temporary")
    with pytest.raises(ValueError):
        bbp.code_archive_files(tmp_path)


def test_fresh_refuses_non_package_directory_without_deleting_it(tmp_path):
    victim = tmp_path / "manuscript"
    victim.mkdir()
    sentinel = victim / "keep.txt"
    sentinel.write_text("keep")
    with pytest.raises(ValueError):
        bbp.fresh(victim)
    assert sentinel.read_text() == "keep"


def test_fresh_clears_only_dedicated_package_child(tmp_path):
    target = tmp_path / "build" / "package" / "main_clean"
    target.mkdir(parents=True)
    (target / "old.aux").write_text("old")
    assert bbp.fresh(target) == target
    assert list(target.iterdir()) == []


def test_fresh_refuses_reparse_ancestor(tmp_path, monkeypatch):
    target = tmp_path / "build" / "package" / "main_clean"
    target.mkdir(parents=True)
    sentinel = target / "keep.txt"
    sentinel.write_text("keep")
    # Windows junctions may need host permissions; simulate only the OS detection boundary.
    original = Path.is_symlink
    monkeypatch.setattr(Path, "is_symlink", lambda p: p == target.parent or original(p))
    with pytest.raises(ValueError):
        bbp.fresh(target)
    assert sentinel.read_text() == "keep"


def test_previous_outer_archives_are_preserved(tmp_path):
    sub = tmp_path / "submission"
    sub.mkdir()
    old = sub / "BIT_Submission_Package_2026-09-13_PRE_SUBMISSION.zip"
    old.write_bytes(b"previous archive")
    sibling = sub / (old.name + ".sha256")
    sibling.write_text("previous checksum")
    history = tmp_path / "build" / "history"
    bbp.preserve_previous_packages(sub, history)
    assert not old.exists()
    assert [p.read_bytes() for p in history.rglob(old.name)] == [b"previous archive"]
    assert [p.read_text() for p in history.rglob(sibling.name)] == ["previous checksum"]


def test_unavailable_font_inspection_is_not_a_pass(tmp_path, monkeypatch):
    from pypdf import PdfWriter
    m = make_manuscript(tmp_path)
    sub = tmp_path / "submission"
    sub.mkdir()
    for name in ("Manuscript_BIT_review.pdf", "Manuscript_BIT_clean.pdf", "Cover_Letter_BIT.pdf", "ESM_1.pdf"):
        writer = PdfWriter()
        writer.add_blank_page(width=300, height=300)
        writer.write(sub / name)
    monkeypatch.setattr(abs_, "fonts_embedded", lambda p: (None, "pdffonts unavailable"))
    # Searchable-text extraction is unrelated to the missing external font inspection.
    monkeypatch.setattr("pypdf._page.PageObject.extract_text", lambda p: "searchable " * 30)
    res = abs_.run_audit(m, submission=sub)
    assert rule(res, "pdfs_readable_searchable_fonts_embedded")["status"] == "FAIL"


def reproduction_fixture(tmp_path):
    m = json.loads((ROOT / "results/bit_revision/manifest.json").read_text())
    for rel in set(m["artifacts"]) | set(m["frozen_inputs_sha256"]):
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / rel, p)
        if rel in m["artifacts"]:
            m["artifacts"][rel] = {"bytes": p.stat().st_size, "sha256": hashlib.sha256(p.read_bytes()).hexdigest()}
    source_files = {"reproduce_bit.py": "# orchestrator\n", "pyproject.toml": "# dependency pins\n",
                    "scripts/verify_bit_claims.py": "# proof code\n"}
    for rel, content in source_files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    m["source_inputs_sha256"] = {rel: hashlib.sha256((tmp_path / rel).read_bytes()).hexdigest() for rel in source_files}
    manuscript = tmp_path / "manuscript"
    manuscript.mkdir()
    (manuscript / "main.tex").write_text("tested article", encoding="utf-8")
    m["manuscript_inputs_sha256"] = {"main.tex": hashlib.sha256((manuscript / "main.tex").read_bytes()).hexdigest()}
    return m


def test_complete_reproduction_manifest_is_accepted_and_does_not_bind_the_cover_letter(tmp_path):
    m = reproduction_fixture(tmp_path)
    letter = tmp_path / "manuscript" / "cover_letter.tex"
    letter.write_text("19 September 2026", encoding="utf-8")
    bbp.validate_reproduction_manifest(tmp_path, m, manuscript=tmp_path / "manuscript")
    letter.write_text("22 September 2026", encoding="utf-8")  # a new letter date needs no new reproduction run
    bbp.validate_reproduction_manifest(tmp_path, m, manuscript=tmp_path / "manuscript")


@pytest.mark.parametrize("corruption", ["artifacts", "frozen", "source", "stage", "test_count", "empty_tests", "command_exit"])
def test_incomplete_reproduction_manifest_is_rejected(tmp_path, corruption):
    m = reproduction_fixture(tmp_path)
    if corruption == "artifacts":
        m["artifacts"] = {}
    elif corruption == "frozen":
        m["frozen_inputs_sha256"].pop(next(iter(m["frozen_inputs_sha256"])))
    elif corruption == "source":
        m.pop("source_inputs_sha256")
    elif corruption == "stage":
        m["stages"].pop()
    elif corruption == "test_count":
        m["tests_passed"] -= 1
    elif corruption == "empty_tests":
        m["tests_passed"] = m["tests_collected"] = 0
    else:
        m["stages"][0]["commands"][0]["exit"] = 1
    with pytest.raises(ValueError):
        bbp.validate_reproduction_manifest(tmp_path, m, manuscript=tmp_path / "manuscript")


@pytest.mark.parametrize("kind", ["artifacts", "frozen_inputs_sha256", "source_inputs_sha256", "manuscript_inputs_sha256"])
def test_reproduction_manifest_rejects_changed_bytes(tmp_path, kind):
    m = reproduction_fixture(tmp_path)
    rel = next(iter(m[kind]))
    base = tmp_path / "manuscript" if kind == "manuscript_inputs_sha256" else tmp_path
    (base / rel).write_bytes(b"changed after reproduction")
    with pytest.raises(ValueError):
        bbp.validate_reproduction_manifest(tmp_path, m, manuscript=tmp_path / "manuscript")


def test_archive_auditor_rejects_compound_temporary_suffix(tmp_path):
    archive = tmp_path / "code.zip"
    with zipfile.ZipFile(archive, "w") as zf:
        zf.writestr("code/main.synctex.gz", b"temporary")
    ok, _ = abs_.zip_rule(archive, False)
    assert not ok


@pytest.mark.parametrize("pending", [
    "Final author approval of this BIT revision is pending.",
    "Final author approval is pending.",
    "Its new public deposit is pending.",
    "Its persistent location remains to be supplied.",
    "The archive is prepared for public release under the MIT License.",
])
def test_final_rejects_pending_prose_after_brackets_removed(tmp_path, pending):
    m = make_manuscript(tmp_path)
    for p in m.glob("*.tex"):
        text = p.read_text()
        for marker in abs_.DELIBERATE_MARKERS:
            text = text.replace(marker, "")
        p.write_text(text)
    p = m / "declarations.tex"
    p.write_text(p.read_text() + "\n" + pending)
    assert rule(abs_.run_audit(m, status="PRE_SUBMISSION"), "package_status_consistent")["status"] == "PASS"
    assert rule(abs_.run_audit(m, status="FINAL"), "package_status_consistent")["status"] == "FAIL"


def test_package_readme_is_neutral_and_the_checklist_stays_in_the_build_record():
    report = {"steps": [
        {"step": "article compiled from flattened source in fresh directories", "clean_pages": 27, "review_pages": 27, "figures": ["Fig1.eps"]},
        {"step": "Online Resource and cover letter compiled", "esm_pages": 17, "cover_pages": 1}]}
    final = bbp.render_readme("FINAL", "2026-09-22", report, ["file"] * 408, True)
    draft = bbp.render_readme("PRE_SUBMISSION", "2026-09-22", report, ["file"] * 408, False)
    # the status stays visible (audit rule package_status_labelled); a draft says that it is not for upload
    assert "status `FINAL`" in final and "22 September 2026" in final and "408 files" in final
    assert "not for upload" not in final and "**Draft package; not for upload.**" in draft
    # every file of the package is described, and the upload / no-upload split is stated
    for name in abs_.SUBMISSION_FILES + ["BIT_Submission_Package_2026-09-22_FINAL.zip"]:
        assert f"`{name}`" in final, name
    assert "Not uploaded: `BIT_ESM_1_Source.zip` and `BIT_Code_and_Data.zip`" in final
    assert "sha256sum -c BIT_SHA256.txt" in final and "reproduce_bit.py all" in final
    # neutral wording: no process jargon, nothing the source auditor would flag
    for word in ("gate", "operator", "fixture", "condition", "staging", "PRE_SUBMISSION", "workspace", "revision", "authoriz", "task "):
        assert word not in final.lower(), word
    for pattern in (abs_.MARKER_WORDS, abs_.BRACKET_MARKER, abs_.PENDING_FINAL_STATUS, abs_.JCP_RESIDUE):
        assert not pattern.search(final), pattern.pattern
    assert not [term for term in abs_.STALE_TERMS if term in final]
    # the checklist goes to build/audit/bit_package.json and never confirms what happens in the journal system
    rows = {r["item"]: r["status"] for r in bbp.author_checklist(True)}
    assert rows[8] == "OPTIONAL" and rows[10] != "CONFIRMED" and rows[11] != "CONFIRMED"
    assert all(rows[i] == "CONFIRMED" for i in (1, 2, 3, 4, 5, 6, 7, 9))
    assert not [r for r in bbp.author_checklist(False) if r["status"] == "CONFIRMED"]


COVER_TEX = r"""\documentclass{article}
\newenvironment{letterbody}{}{}
\begin{document}
{\large\bfseries Ada Lovelace}\\
Uni A\\
\href{mailto:ada@example.org}{ada@example.org}

\vspace{0.3em}\hrule\vspace{0.6em}

22 September 2026

Dear Editor, % a comment

\begin{letterbody}
Please consider ``A good title'' for \textit{BIT Numerical Mathematics}.

A Runge--Kutta step of the classical fourth-order method; it's exact~--- and certified.
\end{letterbody}

Sincerely,

\vspace{1.2em}
{\bfseries Ada Lovelace}\\
Corresponding author
\end{document}
"""


def test_cover_letter_text_keeps_paragraphs_and_whole_words():
    text = bbp.letter_text(COVER_TEX)
    assert text == ("Ada Lovelace\nUni A\nada@example.org\n\n22 September 2026\n\nDear Editor,\n\n"
                    "Please consider “A good title” for BIT Numerical Mathematics.\n\n"
                    "A Runge–Kutta step of the classical fourth-order method; it’s exact — and certified.\n\n"
                    "Sincerely,\n\nAda Lovelace\nCorresponding author\n")
    # the PDF text of the same letter is hard-wrapped, hyphenated at line ends and uses ligatures: same words
    pdf = ("Ada Lovelace\nUni A\nada@example.org\n22 September 2026\nDear Editor,\nPlease consider “A good title” "
           "for BIT Numerical\nMathematics.\nA Runge–Kutta step of the classical fourth-\norder method; it’s exact "
           "— and certiﬁed.\nSincerely,\nAda Lovelace\nCorresponding author\n\f")
    assert bbp.same_letter_text(text, pdf)
    assert not bbp.same_letter_text(text, pdf.replace("certiﬁed", "veriﬁed"))
    # text-symbol commands and a comment after a line break give the same text; unknown commands are refused
    variant = COVER_TEX.replace("Runge--Kutta", "Runge\\textendash Kutta").replace("Uni A\\\\", "Uni A\\\\% note")
    assert bbp.letter_text(variant) == text
    with pytest.raises(ValueError):
        bbp.letter_text(COVER_TEX.replace("Uni A", r"Universit\'e A"))


def test_commented_letterbody_cannot_hide_overlong_real_cover(tmp_path):
    commented_example = "% Count text between \\begin{letterbody} and \\end{letterbody}.\n"
    cover = commented_example + GOOD_COVER.replace("It is short.", " ".join(["word"] * 160))
    res = abs_.run_audit(make_manuscript(tmp_path, **{"cover_letter.tex": cover}))
    result = rule(res, "cover_letter_word_count")
    assert result["status"] == "FAIL"
    assert result["detail"]["words_without_markers"] > 150


def test_pdf_text_preserves_utf8_quotes_and_dashes_under_other_host_locale(tmp_path, monkeypatch):
    expected = "We submit \u201ca paper\u201d\u2014it\u2019s ready.\n"
    real_run = bbp.subprocess.run
    real_which = bbp.shutil.which

    def utf8_tool(argv, **kwargs):
        # Exercise a real UTF-8-producing child while simulating the Windows cp1252 default.
        if kwargs.get("text") and not kwargs.get("encoding"):
            kwargs["encoding"] = "cp1252"
        command = [sys.executable, "-c", f"import sys; sys.stdout.buffer.write({expected.encode('utf-8')!r})"]
        return real_run(command, **kwargs)

    monkeypatch.setattr(bbp.shutil, "which", lambda name: "pdftotext" if name == "pdftotext" else real_which(name))
    monkeypatch.setattr(bbp.subprocess, "run", utf8_tool)
    assert bbp.pdf_text(tmp_path / "cover.pdf") == expected
