#!/usr/bin/env python3
"""Export the compiled article's label numbers for use by the standalone Online Resource.

Reads main.aux (after a complete latexmk run of the article) and writes article_numbers.tex containing
    \\expandafter\\gdef\\csname artnum@<label>\\endcsname{<number>}
for every \\newlabel, plus the accessor \\artnum{<label>}.  ESM_1.tex writes, e.g.,
"article Theorem~\\artnum{thm:rk4}" and therefore can never disagree with the article's numbering.

Usage: python sync_article_numbers.py <main.aux> <article_numbers.tex> [--check]
With --check the script exits 1 if the existing output differs from what the aux file implies.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = "%% Generated by scripts/sync_article_numbers.py from the compiled article's main.aux; do not edit.\n"


def render(aux_text: str) -> str:
    lines = [HEADER, r"\providecommand{\artnum}[1]{\csname artnum@#1\endcsname}", r"\providecommand{\artcite}[1]{\csname artcite@#1\endcsname}", ""]
    labels: dict[str, str] = {}
    for m in re.finditer(r"\\newlabel\{([^}]+)\}\{\{([^{}]*)\}\{([^{}]*)\}", aux_text):
        label, number = m.group(1), m.group(2)
        if label in labels or label.startswith("sub@"):
            continue
        labels[label] = re.sub(r"\\relax\s*", "", number).strip()
    # sorted output: independent of the order in which floats and labels appear in the aux file
    for label in sorted(labels):
        lines.append(rf"\expandafter\gdef\csname artnum@{label}\endcsname{{{labels[label]}}}")
    # numbered citations of the article's reference list (natbib writes \bibcite{key}{{number}{year}{{authors}}{{}}})
    cites = {m.group(1): m.group(2) for m in re.finditer(r"\\bibcite\{([^}]+)\}\{\{(\d+)\}", aux_text)}
    for key in sorted(cites):
        lines.append(rf"\expandafter\gdef\csname artcite@{key}\endcsname{{{cites[key]}}}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    aux, out = Path(argv[0]), Path(argv[1])
    text = render(aux.read_text(encoding="utf-8"))
    if "--check" in argv:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != text:
            print(f"{out} is stale relative to {aux}")
            return 1
        print(f"{out} is synchronized with {aux}")
        return 0
    with open(out, "w", encoding="utf-8", newline="\n") as fh:  # LF on every platform
        fh.write(text)
    print(f"wrote {out} ({text.count('artnum@')} labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
